name: Ontvangst goederen
on:
  schedule:
  - cron: "0 17 * * *"
  workflow_dispatch:

jobs:
  createFile:
    name: Create A File
    runs-on: ubuntu-latest
    steps:
    - uses: "finnp/create-file-action@master"
      env:
        FILE_NAME: "content/fileName.txt"
        FILE_DATA: "file content"
    - name: commit changes
      run: |
        git commit {$FILE_NAME} -m "Auto add file" || echo "no changes to commit"
        git push origin || echo "no changes to commit"
