name: Ontvangst goederen
on:
  schedule:
  - cron: "0 17 * * *"
  - cron: "0 16 5-12 2,8 1"
  workflow_dispatch:

jobs:
  createFiles:
    name: Create all files.
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup git config
        run: |
          sudo locale-gen nl_NL.UTF-8
          sudo update-locale LANG=nl_NL.UTF-8
          git config --global user.name 'Spar Pater'
          git config --global user.email 'Pater2008@users.noreply.github.com'
      - name: Create kalibratie thermometer
        #if: github.event.schedule != '0 17 * * *'
        run: |
          bash ./.github/scripts/kalibratie-thermometer.sh 
          bash ./.github/scripts/kalibratie-thermometer.sh 37
          bash ./.github/scripts/kalibratie-thermometer.sh 36
          bash ./.github/scripts/kalibratie-thermometer.sh 35
          bash ./.github/scripts/kalibratie-thermometer.sh 34
          bash ./.github/scripts/kalibratie-thermometer.sh 33
          bash ./.github/scripts/kalibratie-thermometer.sh 32
          bash ./.github/scripts/kalibratie-thermometer.sh 31

          if [git diff --exit-code -e 1]; then git add .; git commit -am "Automatic add/change file" -m "kalibratie thermometer toegevoegd."; fi
      - name: Create kern temperatuur
        #if: github.event.schedule != '0 16 5-12 2,8 1'
        run: |
          bash ./.github/scripts/kern-temp.sh 
          bash ./.github/scripts/kern-temp.sh 37
          bash ./.github/scripts/kern-temp.sh 36
          bash ./.github/scripts/kern-temp.sh 35
          bash ./.github/scripts/kern-temp.sh 34
          bash ./.github/scripts/kern-temp.sh 33
          bash ./.github/scripts/kern-temp.sh 32
          bash ./.github/scripts/kern-temp.sh 31

          if [git diff --exit-code -e 1]; then git add .; git commit -am "Automatic add/change file" -m "kern temperatuur toegevoegd."; fi
      - name: Create ontvangst goederen
        #if: github.event.schedule != '0 16 5-12 2,8 1'
        run: |
          bash ./.github/scripts/ontvangst-goederen.sh 
          bash ./.github/scripts/ontvangst-goederen.sh 31
          bash ./.github/scripts/ontvangst-goederen.sh 32
          bash ./.github/scripts/ontvangst-goederen.sh 33
          bash ./.github/scripts/ontvangst-goederen.sh 34
          bash ./.github/scripts/ontvangst-goederen.sh 35
          bash ./.github/scripts/ontvangst-goederen.sh 36
          bash ./.github/scripts/ontvangst-goederen.sh 37
          if [git diff --exit-code -e 1]; then git add .; git commit -am "Automatic add/change file" -m "ontvangst goederen toegevoegd."; fi
      - name: Create schoonmaaklijst
        #if: github.event.schedule != '0 16 5-12 2,8 1'
        run: |
          bash ./.github/scripts/schoonmaak.sh 31
          bash ./.github/scripts/schoonmaak.sh 32
          bash ./.github/scripts/schoonmaak.sh 33
          bash ./.github/scripts/schoonmaak.sh 34
          bash ./.github/scripts/schoonmaak.sh 35
          bash ./.github/scripts/schoonmaak.sh 36
          bash ./.github/scripts/schoonmaak.sh 37

          if [git diff --exit-code -e 1]; then git add .; git commit -am "Automatic add/change file" -m "schoonmaaklijst toegevoegd."; fi
      - name: Create temparatuurslijst
        #if: github.event.schedule != '0 16 5-12 2,8 1'
        run: |
          bash ./.github/scripts/temparatuurslijst.sh 
          bash ./.github/scripts/temparatuurslijst.sh 31
          bash ./.github/scripts/temparatuurslijst.sh 32
          bash ./.github/scripts/temparatuurslijst.sh 33
          bash ./.github/scripts/temparatuurslijst.sh 34
          bash ./.github/scripts/temparatuurslijst.sh 35
          bash ./.github/scripts/temparatuurslijst.sh 36
          bash ./.github/scripts/temparatuurslijst.sh 37
          if [git diff --exit-code -e 1]; then git add .; git commit -am "Automatic add/change file" -m "temparatuurslijst toegevoegd."; fi
      - name: Create warmstepuntbepaling
        #if: github.event.schedule != '0 17 * * *'
        run: |
          bash ./.github/scripts/warmstepuntbepaling.sh 
          bash ./.github/scripts/warmstepuntbepaling.sh 31
          bash ./.github/scripts/warmstepuntbepaling.sh 32
          bash ./.github/scripts/warmstepuntbepaling.sh 33
          bash ./.github/scripts/warmstepuntbepaling.sh 34
          bash ./.github/scripts/warmstepuntbepaling.sh 35
          bash ./.github/scripts/warmstepuntbepaling.sh 36
          bash ./.github/scripts/warmstepuntbepaling.sh 37
          if [git diff --exit-code -e 1]; then git add .; git commit -am "Automatic add/change file" -m "warmstepuntbepaling toegevoegd."; fi
      - name: Update main
        run: |
          sleep 10 
          date > README.md
          # Note: the following account information will not work on GHES
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Automatic update README file"
          git push
